#ifndef CPPOQSS_STATE_SYSTEM_NAME_H
#define CPPOQSS_STATE_SYSTEM_NAME_H


#define CPPOQSS_MACRO_STATE_NAME_DENSITYMATRIX "DensityMatrix"

#define CPPOQSS_MACRO_SYSTEM_NAME_ODELINDBLAD "LindbladMasterMPI"


#endif
